### ISSUE TITLE
迁移之后不就意味着要fork你的主题的话需要fork包括你的文章配置所有文件？

### ISSUE THREAD

**Issue by d0zingcat** [xingoxu/hexo-theme-paper-white#1]
总觉得那样很奇怪QAQ
本来想改个主题fork的是paper white的repository，现在变成了fork xingoxu.github.io
好出奇啊。。

> P.S. 

今天本想给博客换个主题因为NexT用久了审美疲劳，然后看了yilia感觉莫名其妙乱七八糟的东西好多。。感觉refine要好久，就准备直接用你的。
然后突然起了个恶作剧的念头：要不我改个Paper-Black粗来？

**Comment by xingoxu** [comment]
对，需要把那整个都clone下来，但只需要里边的theme下的paper-white文件夹

因为之前上了持续集成，所以这里这部分会有一些问题

已经在考虑怎么迁移回来了

**Comment by d0zingcat** [comment]
Well.

正在思考怎么改的更加装逼一些。哈哈。

坐等Fork。

**Comment by xingoxu** [comment]
https://github.com/xingoxu/hexo-theme-paper-white/commit/e8c7c4aaee4b32fbee30c7938601c96f3f9cae86 fixed
